[package]
name = "rsk"
version = "0.1.0"
edition = "2024"

[dependencies]
primitive-types = { version = "0.13.1", features = ["std", "serde"] }
sha3 = "0.10.8"
serde = { version = "1.0.228", features = ["derive"] }
alloy-rlp = "0.3.15"
bitcoin = { version = "0.32", features = ["serde"] }

[dev-dependencies]
chrono = "0.4.44"
serde_json = "1"
hex = "0.4"
